language: node_js
matrix:
  include:
  - node_js:
    - '6'
    env:
    - CAN_DEPLOY=true
script: npm test && npm run build && npm run build:storybook
notifications:
  email:
    on_success: never
deploy:
  provider: npm
  email: accounts@resin.io
  skip_cleanup: true
  api_key:
    secure: tL6tRzDN2331z1yik1UQtH3sKbMtcdqVXO2DNQgrr55/4x5fAq76ZB/pkW4Iiafopb4+OP03CN5Koo+loBDt6MXwi08k/oJwUkPyU3VqAC9AL3RwhPLuSTKQNCeZ/ALQYN2y0kPCr2z1GAvijXPQMzhNJK7nIhWgi6JXMKkxC9K7rVLazJwF4F0ZTYOpI9CCix1kbJfVHwnAX05EDXhdXsvoBLSmBPCAAPJmkOaPgmFsCnoJLXuCJjkBj69pyarwAolAEckrX5Fh6T72+B7NiMZaAAX53rTxZJCyWhKk/kClTBnIBYW35YufCIg+NTHPTrEwyYU+ouUHAsIzRE8TMWUuooolgWmC4ZozR2uphIu5uIWSSRzUlJgQ8z3T1ZOz+KCnSo/H3Si5gurzDSkQ2i9jZLI/B1oCq7DHYdMhC6T8HJnpF1KU3A2n52NWdTvFzD9ws8MtTM7ugBtEGrg/X/+9iTK0Sj+8OWOtnFHxcuTdTcke5A0S2KmgREss1cehYM0PxmGuxbLMe6ZcYAZ0xqhtp4OkjRN0bczymbvPcZqZhwvIbfjD4p1k1xMhtZjlmha15v9hSxNV8mEd/yptFle+f+E7bw1aRPjJFSS6kwxiQqhX8GyEjtiqFPCcUhL+FY9t70gpN6LA3fIdOct5+6KQiS4A1dIotsGuiMqgqPw=
  on:
    tags: true
    condition: $CAN_DEPLOY = 'true' && $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
    repo: resin-io-modules/resin-components
deploy:
  provider: pages
  local_dir: '.out'
  skip_cleanup: true
  github_token:
    secure: ovdIn3BKs1cxs5ESzx+mnZzadi8jGY1CKaAfsq9xYV99LL/9NSs9OlLqukjEyRkUojOy67eJKWARcVh6GLsXEVfNbrgvos6+ZM9H1Fd7ICiB8bWKrNbfEmNF9deTcbyKaTZygse3UGhA+Q9hibCjXkhd5W0oQQGCxzGzWbvXcjgdnliBjvhUqSmKyG75v6ycrG70ETYXlVY8nRzSUOnoav7W5kcrkNoIQNWON8UETwFlMi1dGQrhBsj5Ceb6u6cQsypIeyttWYjQ3uxfbSSqLY2OG3sOaWa1+L0DFo+6gtUBoVVh5vcQFfenXEI3AF4jdrcUV/1ged3QiUdzggELQsPsDiq0pxO5QKMsikyxTUZhhQM4uGCYCsgFb5hJREVLSBBEsqEH5vBFASt23PSL0UIvPFl+uHLH3jVNtj/lip6ryPOGhEP3ZqxjYgTdJiKjIuWF9JCOuuU1tdxdQeMHfNaa+Nv7VAos8sDGpiDjGUOX7GpVTyrCNNUzYPbE5EF5Pf/wRiib7DJfRbErhXN2NOeCkz4L9dSWEntqCdCuFI0gEGNu0LmhsgPoxynCML4FGr/vH4mOtFDFfBmbU+PIp5dYAP6HG4xaUw3QWhxrWOjbtO57jplcNsDpDFJ9c7KiCumDZt9axEou9v1Lx4BhRPegX6rV//NIVip0AsAA0jo=
  on:
    branch: fix-gh-pages-deploy
