sudo: required
services:
  - docker
script: docker build .
notifications:
  email:
    on_success: never
deploy:
  - provider: pages
    local_dir: .out
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master
      tags: true
      condition: $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
env:
  global:
    secure: RMI57fdrPztupNdU2b1whQ50z69mGzCztG4vrSe+Q/FBBz0xSWsGlAEfIrKEq47m5vGXRSD3A7Uz+8FOdvnW13tl1BB33LbilWz4dnmQUdxTpUsVcti0kWkzkfac7BWg+gkbMxe+SmSi+c6XylzSJLnjXrm/SjGSLZW7gdYJaYHtkXcp788MIonxB3ICfWyh9fPE6/AqfHfMLDWGcYlZs0CiyXFfNIqwzL1BnKsIcGoSVSPBLQBXuvfeW7Jg9DFxZ9RYq71xgC2RecfYEdHimstTCC8agfZdFdNxA069bhuxljkcqKA7jhcN9D13/YAtFzhqE9jb31likgNUeGtFgkbQM35xkQ2+p5GxKcFuKXcO/6y+X5Lk57HgGEKHLg4bEXvGMzho0zAKd8U7qGI5RpITvO9ffEbcn99Qjzh0tByfzhbeb8rNXv0JlocOgPipxIQoh/w8oMxtX0C39J67RVQv2G1VixWS8AiRXMiZS0ahJG7e2PmgsRQM1zs74OGcsU8zC2dltTAcgDeDqzr/NXmQLSW4Gp/Lg5H7EpscNXXQcdmVMHVCapNzqjVVXOeqzles0d/M2K/EpVp8+uo3BQKczVVCxN2zm5JEfNBG+EQuCbE9HN+kToX6DF6UXS7t+hN2Sr6p+TPryttnvTYoi4wCQvENz5v61DL052n5nH4=
