language: node_js
node_js:
  - "node"
notifications:
  email:
    on_success: never

install:
  - NODE_ENV=dev npm install

script: npm run ci

on_success:
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && ${TRAVIS_BRANCH} == "master" ]]; then
      npm run publish-storybook
    fi
